import { Tv } from "lucide-react";
import type { Metadata } from "next";
import { ModeToggle } from "../components/mode-toggle";
import { ThemeProvider } from "../components/theme-prodivers";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: "/manifest.json",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="dark:bg-slate-900 dark:text-slate-300">
        <ThemeProvider attribute="class">
          <header className="border-b">
            <div className="dark:text-slate-400 mx-auto max-w-screen-sm px-4 py-2 flex items-center justify-between">
              <h1 className="flex items-center">
                <Tv className="mr-2 h-4 w-4" /> Random episoder
              </h1>
              <ModeToggle />
            </div>
          </header>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
