import { Tv } from "lucide-react";
import type { Metadata } from "next";
import { ModeToggle } from "../components/mode-toggle";
import { ThemeProvider } from "../components/theme-prodivers";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: "/manifest.json",
  themeColor: "white",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="dark:bg-slate-900 dark:text-slate-300">
        <ThemeProvider attribute="class">
          <header className="border-b">
            <div className="dark:text-slate-400 mx-auto max-w-screen-sm px-4 py-2 flex items-center justify-between">
              <h1>
                <Link
                  href="/"
                  className="flex items-center text-slate-500 hover:text-slate-800 hover:dark:text-white group transition"
                >
                  <Tv className="mr-2 h-4 w-4 text-blue-600 dark:text-yellow-400 group-hover:scale-125 group-hover:-rotate-12 transition" />{" "}
                  Simpsons episode picker
                </Link>
              </h1>
              <ModeToggle />
            </div>
          </header>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
